export const posts = [
  {
    id: 1,
    userId: 1,
    title: "Understanding Async/Await in JavaScript",
    content: "Async/Await makes asynchronous code easier to read and write...",
    date: "2024-08-01",
    likes: 150,
    comments: 25,
    shares: 10,
  },
  {
    id: 2,
    userId: 2,
    title: "How to Conduct Effective Product Research",
    content:
      "Product research is essential for developing successful products...",
    date: "2024-08-03",
    likes: 95,
    comments: 40,
    shares: 8,
  },
  {
    id: 3,
    userId: 3,
    title: "Designing User-Centric Interfaces",
    content: "A user-centric interface focuses on the needs of the users...",
    date: "2024-08-02",
    likes: 130,
    comments: 30,
    shares: 15,
  },
  {
    id: 4,
    userId: 4,
    title: "Data Science Trends in 2024",
    content: "The field of data science continues to evolve with new trends...",
    date: "2024-08-04",
    likes: 200,
    comments: 60,
    shares: 25,
  },
  {
    id: 5,
    userId: 5,
    title: "Best Practices for Continuous Integration",
    content:
      "Continuous integration is a key DevOps practice that ensures code quality...",
    date: "2024-08-05",
    likes: 120,
    comments: 20,
    shares: 12,
  },
];
